version: "2"
services:
  web:
    build: .
    image: vue
    container_name: vue
    volumes: 
      - ${PWD}/log:/var/log/nginx/
    environment: 
      - PORT=80
      - TZ=Asia/Bangkok
    ports:
      - 80:80